Repository aws-controllers-k8s/ec2-controller, pull requests merged in 2022-08, with the labels that each got.

#64 Terminal code mappings for VPC resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/vpc/sdk.go
  test/e2e/tests/test_vpc.py
Labels: approved, ok-to-test, lgtm

#66 Removing InvalidVpcId Not Found error from terminal codes
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/vpc_endpoint/sdk.go
Labels: approved, lgtm, needs-ok-to-test

#68 Fix Internet Gateway terminal codes
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/internet_gateway/sdk.go
  test/e2e/tests/test_internet_gateway.py
Labels: approved, ok-to-test, lgtm

#67 Terminal code mappings for Subnet
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/subnet/sdk.go
  test/e2e/tests/test_subnet.py
Labels: approved, ok-to-test, lgtm

#65 Add Rules to Security Group
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/security_group.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ec2.services.k8s.aws_securitygroups.yaml
  generator.yaml
  helm/crds/ec2.services.k8s.aws_securitygroups.yaml
  pkg/resource/security_group/delta.go
  pkg/resource/security_group/hook.go
  pkg/resource/security_group/sdk.go
  templates/hooks/security_group/sdk_create_post_set_output.go.tpl
  templates/hooks/security_group/sdk_file_end.go.tpl
  templates/hooks/security_group/sdk_read_many_post_set_output.go.tpl
  test/e2e/resources/security_group_rule.yaml
  test/e2e/tests/helper.py
  test/e2e/tests/test_security_group.py
Labels: approved, lgtm

#69 Terminal code mappings for RouteTable
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/route_table/sdk.go
  test/e2e/tests/test_route_table.py
Labels: approved, ok-to-test, lgtm

#70 Terminal codes for Security Group
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/security_group/sdk.go
  test/e2e/tests/test_security_group.py
Labels: approved, ok-to-test, lgtm

#72 release artifacts for release v0.0.18
  apis/v1alpha1/ack-generate-metadata.yaml
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#73 refactor vpc_endpoint test to use fixture
  test/e2e/tests/test_vpc_endpoint.py
Labels: approved, lgtm

#74 refactor vpc test to use fixture
  test/e2e/conftest.py
  test/e2e/tests/test_vpc.py
Labels: approved, lgtm

#76 Refactor `ElasticIPAddress` tests to use fixture
  test/e2e/tests/test_elastic_ip_address.py
Labels: approved, lgtm

#75 Refactor `DHCPOptions` tests to use fixture
  test/e2e/tests/test_dhcp_options.py
Labels: approved, lgtm

#79 Refactor `TransitGateway` tests to use pytest fixtures
  test/e2e/tests/test_transit_gateway.py
Labels: approved, lgtm

#80 Refactor `SecurityGroup` tests to use pytest fixtures
  test/e2e/tests/test_security_group.py
Labels: approved, lgtm

#78 Refactor `RouteTable` tests to use fixture
  test/e2e/tests/test_route_table.py
Labels: approved, lgtm

#77 Refactor `InternetGateway` tests to use fixture
  test/e2e/conftest.py
  test/e2e/tests/test_internet_gateway.py
  test/e2e/tests/test_vpc.py
Labels: approved, lgtm

#83 Consolidate pytest markers in e2e tests
  test/e2e/conftest.py
  test/e2e/tests/test_dhcp_options.py
  test/e2e/tests/test_elastic_ip_address.py
  test/e2e/tests/test_internet_gateway.py
  test/e2e/tests/test_security_group.py
  test/e2e/tests/test_vpc.py
Labels: approved, lgtm
