Repository aws-controllers-k8s/ec2-controller, pull requests merged in 2024-09, with the labels that each got.

#216 Avoid SG rules reordering by returning a copy of desired resource when custom update triggers a requeue
  pkg/resource/security_group/hooks.go
Labels: approved, ok-to-test, lgtm

#217 Release artifacts for v1.2.20
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#212 Fix: Add option to delete default SG rule created upon VPC creation
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/vpc.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ec2.services.k8s.aws_vpcs.yaml
  generator.yaml
  go.local.mod
  go.local.sum
  helm/crds/ec2.services.k8s.aws_vpcs.yaml
  pkg/resource/vpc/delta.go
  pkg/resource/vpc/hooks.go
  pkg/resource/vpc/sdk.go
  templates/hooks/vpc/sdk_create_post_set_output.go.tpl
  templates/hooks/vpc/sdk_read_many_post_set_output.go.tpl
  test/e2e/conftest.py
  test/e2e/replacement_values.py
  test/e2e/resources/vpc.yaml
  test/e2e/tests/test_vpc.py
  test/e2e/tests/test_vpc_peering_connection.py
Labels: approved, ok-to-test, lgtm

#218 Release artifacts for v1.2.21
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, ok-to-test, lgtm

#170 Prevent incorrect change in routeTable CR spec after adding route addition having vpcEndpointID
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/route_table/sdk.go
  templates/hooks/route_table/sdk_read_many_post_set_output.go.tpl
Labels: approved, ok-to-test, lgtm

#219 Release artifacts for v1.2.22
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, needs-ok-to-test

#154 Ec2: Network ACL CR should support deletion when subnet association is present
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/network_acl/hooks.go
  pkg/resource/network_acl/sdk.go
  templates/hooks/network_acl/sdk_delete_pre_build_request.go.tpl
  test/e2e/resources/network_acl_with_subnet_assoc.yaml
  test/e2e/tests/test_network_acl.py
Labels: approved, ok-to-test, lgtm

#221 Release artifacts for v1.2.23
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, needs-ok-to-test

#220 Add tests to ensure resource reference is not replaced by controller
  pkg/resource/route_table/hooks.go
  test/e2e/resources/internet_gateway_ref.yaml
  test/e2e/resources/route_table_ref.yaml
  test/e2e/tests/test_references.py
Labels: approved, lgtm

#222 Release artifacts for v1.2.24
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#169 networkAcl update fails if ruleAction field has camelcase Allow/Deny
  pkg/resource/network_acl/hooks.go
Labels: approved, ok-to-test, lgtm

#223 Release artifacts for v1.2.25
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, ok-to-test, lgtm

#157 Fix flowlog crash
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/flow_log/sdk.go
  templates/hooks/flow_log/sdk_create_post_set_output.go.tpl
Labels: approved, ok-to-test, lgtm

#224 Release artifacts for v1.2.26
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, needs-ok-to-test

#225 Fix VPC optional DNS attribute handling
  pkg/resource/vpc/hooks.go
Labels: approved, ok-to-test, lgtm
