Repository aws-controllers-k8s/ec2-controller, pull requests merged in 2024-06, with the labels that each got.

#193 Release artifacts for release v1.2.8
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#194 Set correct `userIDGroupPairs` defaults for `SecurityGroups` CRs.
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/security_group/hooks.go
  pkg/resource/security_group/references.go
  test/e2e/tests/test_security_group.py
Labels: approved, lgtm

#195 Release artifacts for release `v1.2.9`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#196 Refactor and uniform tags comparison/update logic
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/dhcp_options/delta.go
  pkg/resource/dhcp_options/hooks.go
  pkg/resource/elastic_ip_address/delta.go
  pkg/resource/elastic_ip_address/hooks.go
  pkg/resource/flow_log/delta.go
  pkg/resource/flow_log/hooks.go
  pkg/resource/instance/delta.go
  pkg/resource/instance/hooks.go
  pkg/resource/internet_gateway/delta.go
  pkg/resource/internet_gateway/hooks.go
  pkg/resource/nat_gateway/delta.go
  pkg/resource/nat_gateway/hooks.go
  pkg/resource/network_acl/delta.go
  pkg/resource/network_acl/hooks.go
  pkg/resource/route_table/delta.go
  pkg/resource/route_table/hooks.go
  pkg/resource/security_group/delta.go
  pkg/resource/security_group/hooks.go
  pkg/resource/subnet/delta.go
  pkg/resource/subnet/hooks.go
  pkg/resource/transit_gateway/delta.go
  pkg/resource/transit_gateway/hooks.go
  pkg/resource/vpc/delta.go
  pkg/resource/vpc/hooks.go
  pkg/resource/vpc_endpoint/delta.go
  pkg/resource/vpc_endpoint/hooks.go
  pkg/resource/vpc_endpoint_service_configuration/delta.go
  pkg/resource/vpc_endpoint_service_configuration/hooks.go
  pkg/resource/vpc_endpoint_service_configuration/sdk.go
  pkg/resource/vpc_peering_connection/delta.go
  pkg/resource/vpc_peering_connection/hooks.go
  pkg/resource/vpc_peering_connection/sdk.go
  pkg/tags/sync.go
  templates/hooks/vpc_endpoint_service_configuration/sdk_update_pre_build_request.go.tpl
  templates/hooks/vpc_peering_connection/sdk_update_pre_build_request.go.tpl
Labels: approved, lgtm

#197 Release artifacts for release v1.2.10
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#199 Enhance `RouteTable` CRD sync routes synchronisation
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/route_table/hooks.go
  pkg/resource/route_table/sdk.go
  templates/hooks/route_table/sdk_create_post_set_output.go.tpl
  templates/hooks/route_table/sdk_read_many_post_set_output.go.tpl
Labels: approved, lgtm

#200 Release artifacts for release `1.2.11`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#202 fix(networkacl): Correct update order and entries/associations handlers
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/network_acl/hooks.go
  pkg/resource/network_acl/sdk.go
  templates/hooks/network_acl/sdk_create_post_set_output.go.tpl
Labels: approved, lgtm

#201 Release artifacts for release `1.2.12`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm, needs-ok-to-test

#203 fix(securityGroup): groupRef in userIDGroupPairs references id instead of name
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  config/controller/kustomization.yaml
  config/crd/bases/ec2.services.k8s.aws_securitygroups.yaml
  generator.yaml
  helm/crds/ec2.services.k8s.aws_securitygroups.yaml
  helm/templates/NOTES.txt
  pkg/resource/security_group/references.go
Labels: approved, ok-to-test, lgtm

#204 Release v1.2.13
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, ok-to-test, lgtm
