Repository aws-controllers-k8s/ec2-controller, pull requests merged in 2025-03, with the labels that each got.

#250 Generate controller with order tags function
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/capacity_reservation/manager.go
  pkg/resource/capacity_reservation/tags.go
  pkg/resource/dhcp_options/manager.go
  pkg/resource/dhcp_options/tags.go
  pkg/resource/elastic_ip_address/manager.go
  pkg/resource/elastic_ip_address/tags.go
  pkg/resource/flow_log/manager.go
  pkg/resource/flow_log/tags.go
  pkg/resource/instance/manager.go
  pkg/resource/instance/tags.go
  pkg/resource/internet_gateway/manager.go
  pkg/resource/internet_gateway/tags.go
  pkg/resource/nat_gateway/manager.go
  pkg/resource/nat_gateway/tags.go
  pkg/resource/network_acl/manager.go
  pkg/resource/network_acl/tags.go
  pkg/resource/route_table/manager.go
  pkg/resource/route_table/tags.go
  pkg/resource/security_group/manager.go
  pkg/resource/security_group/tags.go
  pkg/resource/subnet/manager.go
  pkg/resource/subnet/tags.go
  pkg/resource/transit_gateway/manager.go
  pkg/resource/transit_gateway/tags.go
  pkg/resource/vpc/manager.go
  pkg/resource/vpc/tags.go
  pkg/resource/vpc_endpoint/manager.go
  pkg/resource/vpc_endpoint/tags.go
  pkg/resource/vpc_endpoint_service_configuration/manager.go
  pkg/resource/vpc_endpoint_service_configuration/tags.go
  pkg/resource/vpc_peering_connection/manager.go
  pkg/resource/vpc_peering_connection/tags.go
Labels: approved, lgtm

#236 Issue 2090/route table order dependence
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  go.mod
  pkg/resource/route_table/delta.go
  pkg/resource/route_table/hooks.go
  pkg/resource/route_table/hooks_test.go
Labels: approved, ok-to-test, lgtm

#253 fixing default rule tests
  test/e2e/tests/test_network_acl.py
Labels: approved

#252 feat(NetworkACL): Filter Default Rules from Delta
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/capacity_reservation/delta.go
  pkg/resource/capacity_reservation/manager.go
  pkg/resource/capacity_reservation/tags.go
  pkg/resource/dhcp_options/delta.go
  pkg/resource/dhcp_options/manager.go
  pkg/resource/dhcp_options/tags.go
  pkg/resource/elastic_ip_address/delta.go
  pkg/resource/elastic_ip_address/manager.go
  pkg/resource/elastic_ip_address/tags.go
  pkg/resource/flow_log/delta.go
  pkg/resource/flow_log/manager.go
  pkg/resource/flow_log/tags.go
  pkg/resource/instance/delta.go
  pkg/resource/instance/manager.go
  pkg/resource/instance/tags.go
  pkg/resource/internet_gateway/delta.go
  pkg/resource/internet_gateway/manager.go
  pkg/resource/internet_gateway/tags.go
  pkg/resource/nat_gateway/delta.go
  pkg/resource/nat_gateway/manager.go
  pkg/resource/nat_gateway/tags.go
  pkg/resource/network_acl/delta.go
  pkg/resource/network_acl/hooks.go
  pkg/resource/network_acl/manager.go
  pkg/resource/network_acl/tags.go
  pkg/resource/route_table/delta.go
  pkg/resource/route_table/manager.go
  pkg/resource/route_table/tags.go
  pkg/resource/security_group/delta.go
  pkg/resource/security_group/manager.go
  pkg/resource/security_group/tags.go
  pkg/resource/subnet/delta.go
  pkg/resource/subnet/manager.go
  pkg/resource/subnet/tags.go
  pkg/resource/transit_gateway/delta.go
  pkg/resource/transit_gateway/manager.go
  pkg/resource/transit_gateway/tags.go
  pkg/resource/vpc/delta.go
  pkg/resource/vpc/manager.go
  pkg/resource/vpc/tags.go
  pkg/resource/vpc_endpoint/delta.go
  pkg/resource/vpc_endpoint/manager.go
  pkg/resource/vpc_endpoint/tags.go
  pkg/resource/vpc_endpoint_service_configuration/delta.go
  pkg/resource/vpc_endpoint_service_configuration/manager.go
  pkg/resource/vpc_endpoint_service_configuration/tags.go
  pkg/resource/vpc_peering_connection/delta.go
  pkg/resource/vpc_peering_connection/manager.go
  pkg/resource/vpc_peering_connection/tags.go
Labels: approved

#251 feat: new resource - TransitGatewayVPCAttachment
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/transit_gateway_vpc_attachment.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/ec2.services.k8s.aws_transitgatewayvpcattachments.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/ec2.services.k8s.aws_transitgatewayvpcattachments.yaml
  helm/templates/_helpers.tpl
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/transit_gateway_vpc_attachment/delta.go
  pkg/resource/transit_gateway_vpc_attachment/descriptor.go
  pkg/resource/transit_gateway_vpc_attachment/hooks.go
  pkg/resource/transit_gateway_vpc_attachment/identifiers.go
  pkg/resource/transit_gateway_vpc_attachment/manager.go
  pkg/resource/transit_gateway_vpc_attachment/manager_factory.go
  pkg/resource/transit_gateway_vpc_attachment/references.go
  pkg/resource/transit_gateway_vpc_attachment/resource.go
  pkg/resource/transit_gateway_vpc_attachment/sdk.go
  pkg/resource/transit_gateway_vpc_attachment/tags.go
  templates/hooks/transit_gateway_vpc_attachment/sdk_create_post_build_request.go.tpl
  templates/hooks/transit_gateway_vpc_attachment/sdk_update_post_build_request.go.tpl
  templates/hooks/transit_gateway_vpc_attachment/sdk_update_pre_build_request.go.tpl
  test/e2e/bootstrap_resources.py
  test/e2e/requirements.txt
  test/e2e/resources/transitgateway_vpc_attachment.yaml
  test/e2e/service_bootstrap.py
  test/e2e/tests/helper.py
  test/e2e/tests/test_transitgateway_vpc_attachment.py
Labels: approved, lgtm

#256 fix: remove printf with no constant
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/vpc_peering_connection/sdk.go
  templates/hooks/vpc_peering_connection/sdk_update_pre_build_request.go.tpl
Labels: approved, lgtm
